modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT-CODE, ARR-ART"

[[mods]]
modId="unify"
version="${file.jarVersion}"
displayName="Create: Unify"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="pack.png"
#credits=""
authors="LopyLuna"
description='''
YIPPEE WASSUP THIS HURTS MY HEAD LMAO
'''

[[dependencies.unify]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unify]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="AFTER"
    side="BOTH"